server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Redireciona requisições de rotas não físicas para o index.html (essencial para SPAs)
        try_files $uri $uri/ /index.html;
    }

    # Tratamento de erro 50x
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
